const { PrismaClient } = require('@prisma/client');
const fs = require('node:fs');
const path = require('node:path');
const prisma = new PrismaClient();
(async () => {
  const p = await prisma.paper.findUnique({ where: { id: '2024-prediction-1' }, include: { sections: { orderBy: { sortOrder: 'asc' }, include: { options: true, tasks: { orderBy: { sortOrder: 'asc' }, include: { questions: { orderBy: { questionNumber: 'asc' }, include: { options: true, answerRules: true, sourceReferences: true } } } } } } } });
  const payload = { paperId: p.id, title: p.title, courseCode: p.courseCode, year: p.year, month: p.month, region: p.region, paperType: p.paperType, totalScore: p.totalScore, suggestedMinutes: p.suggestedMinutes, verified: false, status: 'draft', publishBlocked: true, sourceFile: p.sourceFile || undefined, sections: p.sections.map(s => ({ type: s.type, title: s.title, sortOrder: s.sortOrder, passage: s.passage || undefined, instructions: s.instructions || undefined, scorePerQuestion: s.scorePerQuestion, optionsPool: s.tasks.every(t => t.questions.every(q => q.options.length)) ? [] : s.options.map(o => ({ key: o.key, content: o.content })), tasks: s.tasks.map(t => ({ title: t.title || undefined, sortOrder: t.sortOrder, instructions: t.instructions || undefined, questions: t.questions.map(q => ({ questionNumber: q.questionNumber, stem: q.stem, baseWord: q.baseWord || undefined, originalStem: q.originalStem || undefined, scoreValue: q.scoreValue, verified: false, options: q.options.map(o => ({ key: o.key, content: o.content })), answerRules: q.answerRules.map(r => ({ standardAnswer: r.standardAnswer, originalAnswer: r.originalAnswer || undefined, acceptableAnswers: JSON.parse(r.acceptableAnswers || '[]'), caseSensitive: r.caseSensitive, explanation: r.explanation || undefined, disputed: r.disputed, revisionNotes: r.revisionNotes || undefined })), sourceReferences: q.sourceReferences.map(r => ({ sourceFileName: r.sourceFileName, pageNumber: r.pageNumber || undefined, extractionMethod: r.extractionMethod || undefined, correctionNotes: r.correctionNotes || undefined })) })) })) })) };
  const destination = path.join(__dirname, '../prisma/seed-data/repaired-preview-20260910.json');
  fs.writeFileSync(destination, JSON.stringify(payload, null, 2) + '\n', { flag: 'wx' });
  console.log(destination);
})().finally(() => prisma.$disconnect());
